apiVersion: v1
kind: Secret
metadata:
  name: "github"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: '<username>'
  password: '<password>'
---
apiVersion: v1
kind: Secret
metadata:
  name: "dockerhub"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: '<username>'
  password: '<password>'
