AWSTemplateFormatVersion: 2010-09-09

Description: Continuous deployment infrastructure

Resources:
  CodeBuildeImageEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: codebuild_image
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:GetRepositoryPolicy
              - ecr:SetRepositoryPolicy
